### PR TITLE
Fix for Main group

### LINKED ISSUE #54: Enable 'Inner blocks use content width' for the main Groups
### Description

As discussed on [Slack](https://vertistudio.slack.com/archives/C04CP8FPNNA/p1688719175022669), the sections on each page are imported as a Main Group, but this makes it look like the whole page has a Padding.

In order to mitigate this, we need to enable the **Inner blocks use content width** for the main groups, which will make the Padding invisible in the Editor.

### Step-by-step reproduction instructions

1. Create a fresh instance
2. Install Neve FSE 1.0.3
3. Open the Front Page in edit mode and notice the visible Padding in the Editor

### Screenshots, screen recording, code snippet or Help Scout ticket

Screenshot 2023-07-07 at 11 37 07
Screenshot 2023-07-07 at 11 34 09

Screenshot 2023-07-07 at 11 31 57

___

The setting that needs to be enabled:
image

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by mghenciu**
### Summary

This fixes the issue where the main group for all the templates, has some padding on the sides in the editor.
After the fix, there should be no padding in the Editor.

### Will affect visual aspect of the product

YES, In the Editor only

___
### Screenshots 

Screenshot 2023-07-13 at 09 51 33

___

Screenshot 2023-07-13 at 09 53 04

___
### Test instructions

- Install the build
- open a few templates like 404, front page, index, etc
- see if the main group has **Enabled Inner blocks use content width** and/or a transparent bg color set
- in case the 2 things mentioned above are checked -> the Main Group shouldn't have any padding on the side in the Editor

Closes #54 .

### CODE REVIEW

**Review by preda-bogdan — APPROVED** [review]
Code changes look good, we can move this to QA for testing.

**Comment by rodica-andronache** [comment]
@mghenciu On desktop everything looks ok. I'm wondering if the way it now looks on mobile is ok ( with some sections that don't have any left/right padding ).
Some examples of how it's looking with this PR compared to the current version:
https://vertis.d.pr/i/0rHptW VS https://vertis.d.pr/i/v3CKWw
https://vertis.d.pr/i/XUslY3 VS https://vertis.d.pr/i/rST7tk
Let me know if that's expected or not. Thanks!

**Comment by mghenciu** [comment]
Thank you Rodica for checking so promptly.
Yes, you are right - there looks to be some changes on Mobile. I'll review this more, and when ready move again into QA.
Sorry for the inconvenience.

___

@JohnPixle , apparently using **Inner blocks use content width** with Neve FSE - there's also a visual issue when previewing Core Styles (attached):
Screenshot 2023-07-13 at 16 25 58

Now, I did some testing with Spectra one (which doesn't uses one main group) and with Frost (which has a main group). And what I noticed in case of Frost, is that they use **Inner blocks use content width** with all groups, in some they even have values; additionally they use custom padding on the sides - which we don't. Added a video below with Frost:



Let me know what you think.
I'll try to test a few more approaches in terms of padding.

**Comment by cristian-ungureanu** [comment]
@mghenciu I will close this PR since the fix was provided in this PR: https://github.com/Codeinwp/neve-fse/pull/75

**Pull request closed without merging**
