### PR TITLE
Changes the color styles of the sections on the homepage + Adds new Styles

### LINKED ISSUE #71: Add 3-4 Theme Style Presets
### What problem does this address?

As discussed on Slack - we can **improve** the existing styles focusing on how the overall site looks and the Thumbnail preview  + add new ones.
Maybe try something with the Gradients also.

We can also merge [this PR](https://github.com/Codeinwp/neve-fse/pull/59).

### What is your proposed solution?

_No response_

### Will this feature require documentation? (Optional)

None

### PR DESCRIPTION
**Pull request by mghenciu**
### Will affect visual aspect of the product

YES

### Screenshots 

**Before**

Screenshot 2023-07-18 at 14 44 41

___

**After**
Screenshot 2023-07-18 at 14 42 29

### Test instructions

- Install Neve FSE on a fresh instance
- Add the build
- see the new background colors for the 3 sections on the homepage (columns with icons, image and text, text and image)
- test the 4 new Styles: Tiber, Hippie green, Blaze orange, Monochrome blue
- test that Hero image has a Duotone filter, which should make the hero look better - even when the color is not matching blue

Closes #71 .

This should fix the issue where in the WP repo, previewing colors will make the Nav Bar look different compared to the Icons section (examples below where it's visible that things can be improved):

<details><summary>Images</summary>

Screenshot 2023-07-18 at 14 46 38

___

Screenshot 2023-07-18 at 14 47 18

</details>

Closes #71 

___

@JohnPixle , when you have some time, please let me know if this is ok - and I'll pass it to testing. 🙇 
After this I'll create also a new PR with more color styles and small updates on the current ones.

### CODE REVIEW

**Comment by mghenciu** [comment]
@JohnPixle , I finished experimenting here. When you have some time, please take a look.
Here's a quick vide with styles: 

https://github.com/Codeinwp/neve-fse/assets/52494172/670c2617-37d2-4625-b8c3-34c27fbd290a

<details><summary>Duotone example</summary>


https://github.com/Codeinwp/neve-fse/assets/52494172/29204fec-2863-41ce-ae5a-65ae0610b902



</details>



### Key changes
- added **4 new Styles**: Tiber, Hippie green, Blaze orange, Monochrome blue
- **added the accent color in the testimonials** in this [PR](https://github.com/Codeinwp/neve-fse/pull/77), to make the bottom area more expresive 
- defined and added **Button variations** (only) for the new palettes. Didn't touched the old ones (mentioned at the end why)
- added **Duotone** filter on the Hero area, which should make the hero look better - even when the color is not matching blue 

___

### Other comments
Other things that I noticed while doing testing, and I think we need to address those (I can make issue if you agree):
- there's **no hover or focus** state for buttons overall. I tried adding hover using `rgba(var(--color), 0.8);` but it didn't worked. 
- additionally, accessibility wise - for some reason it's not possible now to go through the content on the Homepage. In 2023 theme, it's possible to do this using the Tab key.
- overall, we can have different Styles for Buttons and Typography - which may be nice. But for now I only did this changes on the new palettes, since I am not sure if changing the other ones will affect the user sites. **We need to be sure about this, before doing any changes on the existing palettes.**

___

### For the Dev team before merging
- I need some help with the spacing between blocks in the Editor, somehow I got to the point where the Blocks in the Editor - don't have any space between them (vertically), compared to the live site
- also, since I've added the option to have different button styles for each palette - right now the Outline buttons look smaller in the editor for some reason, and I couldn't fix it. Essentially the buttons (primary and outline) should inherit the default style from theme.json, but if something else is defined in the used Palette -> use the style from there. The last comments [from here](https://github.com/WordPress/gutenberg/issues/34853) could give a solution. 
- I know it's not recommended, but I did pulled the changes that Cristi made to fix the padding and section height

cc @HardeepAsrani

**Review by HardeepAsrani — APPROVED** [review]
Changes look good @mghenciu. One small recommendation would be to use either tabs or spacing when making changes to JSON file, you can also do it automatically from the code editor, or we can implement an editorconfig for this.

As discussed, the mentioned issues don't happen with this + latest WP.

**Comment by irinelenache** [comment]
@mghenciu Tested and found only one thing, don't know if it's an actual issue:

- [ ] If i use a darker image as the hero image, the text color there will change to white, which doesn't look ideal when the duotone filter is used https://vertis.d.pr/i/TMFdD7 

If it's safe to leave it like this, let me know and i'll move this to **Ready to merge** 🚀

**Comment by irinelenache** [comment]
@JohnPixle Thanks for the clarification 🙏 

> In my instance, I also noticed that despite the fact that I am using theme colors in a duotone filter, the color is not dynamically preserved when switching theme styles. Does it happen to you as well?

^ I checked now and it happens to me also

**Comment by mghenciu** [comment]
> In my instance, I also noticed that despite the fact that I am using theme colors in a duotone filter, the color is not dynamically preserved when switching theme styles. Does it happen to you as well?

When you have some time, @JohnPixle , could you please share a bit more details about this.

I've tried changing the duotone, but I think you are referring to something else:

https://github.com/Codeinwp/neve-fse/assets/52494172/33e9def6-c57f-4b02-afae-f6d0756da4dd

**Comment by irinelenache** [comment]
@mghenciu @JohnPixle For me the issue was something like this:
- If i change the duotone colors and select the theme's **Background** color for **Shadows**, the color won't dynamically change after switching the style. I would expect to have the background color from the second style that i selected. Here is a video with the behaviour https://vertis.d.pr/v/whX7tX , let me know if i misunderstood anything 🙏

**Pull request closed without merging**
