### PR TITLE
Feat: design changes

### PR DESCRIPTION
**Pull request by preda-bogdan**

### CODE REVIEW

**Comment by preda-bogdan** [comment]
@JohnPixle It looks like something local to your instance and not related to the build. What other changes have you made on that instance?

**Comment by preda-bogdan** [comment]
@JohnPixle Your error was caused by a template part that you might have added when testing that did not now have the register type. It was the page title cover template part that I removed.

**Comment by preda-bogdan** [comment]
@mghenciu I think we are aiming for a 6.1+ it doesn't make any sense in my opinion to go any lower. 
@selul Keeping you in the loop. Should we support lower than 6.1?

**Comment by selul** [comment]
Nope, I'm good with 6.1+

**Comment by preda-bogdan** [comment]
@Codeinwp/qa-team Hello, when you have some time can you help with testing this PR in anticipation of the release?

### How to test:
1. On a fresh instance, check how the theme behaves and works and if you encounter any issues in creating a website. We can apply the same testing workflow as for our other FSE themes.
2. In addition we can also check how the theme works when moving from an existing instance of Neve, there should not be any major issues and some of the settings will be ported, e.g. Colors, some basic Typography options, and Basic Fonts, however, this is not a priority if options are missing as long as the transition is smooth and things are not breaking.
3. Check the included theme patterns that are available under Neve FSE Patterns
4. Check the layout variants that are available under Neve FSE Layouts (these are used to replace the main groups for the Single and Archive pages). They work as an alternative to the default templates. 
    The workflow is to remove the group between the Header and the Footer from the Site Editor and replace it with a layout variant.


Let me know if you require more details or if you have any questions.
Thank you!

**Comment by preda-bogdan** [comment]
@rodica-andronache Solved the mentioned issues. @mghenciu the portfolio issue was caused by the background dim, I changed the value to 10 instead of 16 as it needs to be divisible by 10.

Link any other issues you find and I will solve them as soon as possible.
Thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle I agree. I've updated the templates to also contain the title.

**Comment by rodica-andronache** [comment]
@preda-bogdan had another look, and the only thing I saw is this: When using the **Archive List layout**, the posts are listed correctly, but you can’t access the single post page by any way, as neither the title, content or image are linked
https://vertis.d.pr/i/VOO0as

**Comment by preda-bogdan** [comment]
@rodica-andronache this only happens for the **Archive List Layout** right?

**Comment by rodica-andronache** [comment]
@preda-bogdan yes

**Comment by rodica-andronache** [comment]
@preda-bogdan it's working well. Had another look, and noticed another small thing.  On mobile, or smaller devices, the buttons from the Otter notice are not properly aligned https://vertis.d.pr/i/lHkTpV. Also, on tablet, the whole notice is quite big, maybe the image could be hidden there

**Comment by preda-bogdan** [comment]
@rodica-andronache thank you, for looking into this. I will have a look as I think that we use the same notice on other FSE themes so it might need fixing across the board. Good catch! 🚀

**Comment by preda-bogdan** [comment]
@rodica-andronache Should be solved now, on this theme. Thank you for reporting this.

**Pull request merged**
